In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('/home/mdnaim/Github/100-days-of-machine-learning/Placement.csv')

In [5]:
df

    Student_ID  CGPA   IQ  Placement
0            1   6.8  123          1
1            2   5.9  106          0
2            3   5.3  121          0
3            4   7.4  132          1
4            5   5.8  142          0
..         ...   ...  ...        ...
95          96   4.3  200          0
96          97   4.4   42          0
97          98   6.7  182          1
98          99   6.3  103          1
99         100   6.2  113          1

[100 rows x 4 columns]

In [7]:
df.head()

   Student_ID  CGPA   IQ  Placement
0           1   6.8  123          1
1           2   5.9  106          0
2           3   5.3  121          0
3           4   7.4  132          1
4           5   5.8  142          0

In [9]:
df.shape

(100, 4)

# Steps
## 0. Preprocess + EDA + Feature Selection
## 1. Extract Input and output columns
## 02. Scale the values
## 03. Train test values
## 04. Train the model
## 05. Evaluate the model/model selection
## 06. Deploy the mdel